Hw1
made-mlops-2022/vladyslav_gadzikhanov pull request #3
Opened 2022-11-06 15:55 UTC by VladGadzikhanov

MADE

1) Основные моменты описаны в README.md.
2) Добавить CI и Hydra для конфигов планирую до hard-дедлайна.

2022-11-25 16:06 UTC, nickdndev commented
добавить самооценку

2022-11-25 16:06 UTC, nickdndev commented
![image](https://user-images.githubusercontent.com/49230518/204022142-55255994-e23a-49c4-bec0-1de16be3b501.png)
добавить в гитигнор , кеш не должен уходить в мастер

2022-11-25 16:09 UTC, nickdndev requested changes

2022-11-25 16:09 UTC, nickdndev commented on mlops_hw1/custom_transformer/transformer.py
> +                pass
точно надо подавлять ошибку ?

2022-11-26 10:26 UTC, VladGadzikhanov commented on mlops_hw1/custom_transformer/transformer.py
> +                pass
Да, логика в том, что она будет возникать в нечисловых колонках...

2022-11-26 11:24 UTC, VladGadzikhanov commented
> MADE
      1.0) Не совсем понимаю, что нужно было сделать в этом пункте, надеюсь, что прописал необходимые вещи тут.  
    1.1) Самооценка ниже.  
    1.2) Разведочный анализ данных:  
	     1.2.1)  mlops_hw1/notebooks/manual_eda: ручками сделанный.  
	     1.2.2)  mlops_hw1/notebooks/script_eda: с помощью скрипта.  
    1.3) Функция для тренировки модели: models/model_fit_predict.py/train_model, инструкция ниже.                  			                       1.4) Функция для прогнозов: models/model_fit_predict.py/predict_model, инструкция ниже.  
    1.5) Модульная структура.  
    1.6) Логгеры:  
	     1.6.1) Задается конфигурация: mlops_hw1/models/defining_logger_configuration.py.  
	     1.6.2) Файл для записи: mlops_hw1/file_handler.log.  
    1.7) Тесты: mlops_hw1/tests.  
    1.8) Генерация приближенных к реальным данных для тестов: mlops_hw1/data_generation.  
    1.9) Конфиги: mlops_hw1/configs.  
	     1.9.1) first_config.yaml: CatBoostClassifier.  
	     1.9.2) second_config.yaml: LogisticRegression.  
    1.10) Датаклассы: mlops_hw1/enties.  
    1.11) Самописный трансформер:  
	     1.11.1) Сам трансформер: mlops_hw1/custom_transformer/transformer.py.  
	     1.11.2) Тесты: mlops_hw1/tests/test_transformer.  
    1.12) Зависимости: mlops_hw1/requirements.txt.  
    1.13) ---.  
  
Сделано все, кроме 13 пункта и доп. части.

2022-12-04 18:16 UTC, nickdndev commented
итог: 30 -1(кеш так не был удален из MR) = 29

2022-12-04 18:16 UTC, nickdndev approved these changes

2022-12-10 21:25 UTC, VladGadzikhanov commented
Вроде же удалил кэш?

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/87336337/206875776-d9cfe370-c424-4716-826d-c30e5c7f7daa.png">

2022-12-15 22:15 UTC, nickdndev commented
![image](https://user-images.githubusercontent.com/49230518/207978669-3609920b-fb14-4894-8001-6c8e4ef9f20c.png)
вижу MR

2022-12-15 22:15 UTC, nickdndev approved these changes

2022-12-16 13:07 UTC, merged