hw3 added
made-mlops-2022/vladyslav_gadzikhanov pull request #5
Opened 2022-12-04 17:49 UTC by VladGadzikhanov

Сделано все, кроме 3-го пункта и доп. части. 26 баллов.
![2022-12-04 8 48 49 PM](https://user-images.githubusercontent.com/87336337/205506930-56b348d1-be78-454f-a84d-96088258039c.jpg)
![2022-12-04 8 49 00 PM](https://user-images.githubusercontent.com/87336337/205506931-384cf12d-33a1-4ae2-8abd-6ef132f181b8.jpg)
![2022-12-04 8 49 03 PM](https://user-images.githubusercontent.com/87336337/205506933-82789784-2916-4a3d-88d2-7ca247d510b5.jpg)

2022-12-07 08:28 UTC, bulaevvi requested changes
На общем скриншоте (самый нижний) видно, что сработал только один даг - data_generation, соответственно зачесть я могу только его. Если хотите баллов за второй даг, то надо переделать общий скриншот, чтобы было видно, что второй даг тоже сработал.

См. пример в дискорде https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946

2022-12-07 10:26 UTC, bulaevvi commented
Прикрепите пожалуйста скриншоты прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

2022-12-07 14:51 UTC, VladGadzikhanov commented
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/87336337/206210816-4efcd9ae-c451-48f7-94f9-ab779bc67210.png">

2022-12-11 07:29 UTC, VladGadzikhanov commented
Спасибо за проверку!)

2022-12-11 07:29 UTC, merged